### ISSUE TITLE
Installation Issue ? How to Solve?

### ISSUE THREAD

**Issue by selvakarna** [ixmilia/iges#4]
sudo apt-get install dotnet-sharedframework-microsoft.netcore.app-1.0.3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package dotnet-sharedframework-microsoft.netcore.app-1.0.3
E: Couldn't find any package by glob 'dotnet-sharedframework-microsoft.netcore.app-1.0.3'
E: Couldn't find any package by regex 'dotnet-sharedframework-microsoft.netcore.app-1.0.3'

**Comment by brettfo** [comment]
Turns out I had old instructions in README.md.  I've updated the instructions.
