### ISSUE TITLE
Migrate to MIT license

### ISSUE THREAD

**Issue by brettfo** [ixmilia/iges#7]
I'd like to migrate this repo to be under the MIT license, but as I understand it I need the permission of all contributors.

@RSchwarzwald-Hexagon Are you OK with relicensing this repo as MIT?  Looking through the commit history, the relevant commits are:
- Added IgesSingularSubfigureInstance (036a0dea82ee9dab732c00be330f062194e2cf0c)
- Added IgesNameProperty (980aace64319f13bd6118ce84cbf71381c0427c9)
- Added CultureInfo.InvariantCulture to the ParameterReader for doubles… (760dca4837c1dcb572900b5f24a13fc10fcbe267)

If you're good with it, can you add a comment saying so?

**Comment by RSchwarzwald-Hexagon** [comment]
Fine by me.
