### ISSUE TITLE
precompiled binary or NuGet

### ISSUE THREAD

**Issue by xyont** [IxMilia/Iges#9]
hi,

interesting to try and use this libraray, is there any link to precompiled binary or NuGet?

regards,

**Comment by brettfo** [comment]
Currently this library only exists as source code here on GitHub.  Eventually I plan on publishing packages to nuget.org, but there are still some unimplemented entity types, specifically:

- Type 114, parametric splice surface needs clarification
- Type 316
- Type 320
- Type 322
- Type 402, all forms _except_ form 5
- Type 404
- Type 406
- Type 408
- Type 410
- Type 412
- Type 414
- Type 416
- Type 418
- Type 420
- Type 422
- Type 430
- Type 502
- Type 504
- Type 508
- Type 510
- Type 514

**Comment by xyont** [comment]
thanks for clarify,, at least  the binary is available in GitHub even limited features.
